title: "有趣的博客"
languageCode: "zh-CN"
baseurl: "http://gozkj.com"
copyright: "Copyright (c) 2015-2016. zhaokaiju All rights reserved."
theme: "hugo-rapid-theme"
MetaDataFormat: "yaml"
canonifyurls: true
builddrafts: false
PaginatePath: paginator
pygmentsStyle: "default"
pygmentsUseClasses: true
RSSUri: "feed.xml"
disablePathToLower: true 
hasCJKLanguage: true
permalinks:
  posts: /:year/:month/:day/:slug/
Taxonomies:
  tag: "tags"
  category: "categories"
params:
  CopyrightHTML: "Copyright &#xA9; 2015-2016. zhaokaiju All Rights Reserved."
  GitHubUser: "coderzh"
  SidebarRecentLimit: 5
  DateForm : "2006年01月02日"
  Tagline: "有趣的博客"
  Description: "高效率，慢生活。"
  Keywords: "独立博客,程序员,思考,读书笔记,技术分享"
  Categories:
    - "读书笔记"
    - "技术文章"
    - "思考感悟"
menu:
  main:
      - Name: "归档"
        Pre: "<i class='fa fa-heart'></i>"
        Weight: -110
        Identifier: "post"
        URL: "/post/"
      - Name: "关于我"
        Pre: "<i class='fa fa-road'></i>"
        Identifier: "about"
        Weight: -100
        URL: "/about/"
author:
  name: "CoderZh"

images:
  - 480x
  - 768x
  - 960x
  - 1024x
  - 1920x
  - 720x340
  - 520x245
